name: random_users_surf
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  elementary: ^1.3.1
  get_it: ^7.2.0
  dio: ^4.0.6
  shimmer: ^2.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  surf_lint_rules: ^1.5.0
  elementary_test: ^1.1.2

flutter:

  uses-material-design: true
